name = "flutter-theme-generator"
main = "src/worker.js"
compatibility_date = "2025-07-26"

# Static assets configuration for Workers
[site]
bucket = "./dist"
include = ["**/*"]
exclude = []

# Environment variables
[env.production.vars]
ENVIRONMENT = "production"

[env.preview.vars]
ENVIRONMENT = "preview"

# KV namespace for static assets
[[kv_namespaces]]
binding = "STATIC_ASSETS"
id = "8b7d5638811649a7a388b654d2dbdf6d"
preview_id = "8b7d5638811649a7a388b654d2dbdf6d"

# Build configuration
[build]
command = "npm run build"
cwd = "./"
watch_dir = "src"

# Custom domain routes (add your domain here)
[[routes]]
pattern = "flutter.minimalistposter.studio/*"
zone_name = "minimalistposter.studio"

[observability.logs]
enabled = true